### PR TITLE
Resolve to many IP addresses, check them one by one on connect

### LINKED ISSUE #746: can: try several IP addresses for one host if one fails
The easiest strategy would be to try all the available addresses in a round-robin fashion on failed connection attempts and probably make the strategy configurable.

See https://groups.google.com/d/msg/spray-user/d6XNRVfjGpo/Y3UURzz4mewJ

### PR DESCRIPTION
**Pull request by fernandezpablo85**
Fixes #746

### CODE REVIEW

**Comment by sirthias** [comment]
This PR has been sitting around for far too long, given the value that it provides.
However, as @jrudolph already said before, we won't be merging it into spray anymore.
Rather, we'll use it as a basis for clearing the equivalent of https://github.com/spray/spray/issues/746 on the Akka side.

Thanks again, @fernandezpablo85, your contribution is still very much appreciated.
If you like you are also very welcome to resubmit this patch against the [`release-2.3-dev` branch of the Akka codebase](https://github.com/akka/akka/tree/release-2.3-dev). Otherwise we will simply turn to your code when closing the ticket in Akka.

**Comment by fernandezpablo85** [comment]
@sirthias  I'll resubmit the patch to the akka repository soon.

**Comment by sirthias** [comment]
Great! Thanks @fernandezpablo85 !

**Comment by fernandezpablo85** [comment]
@sirthias I have checked the akka code and has changed substantially since this pull request, it's hard for me to move the patch there. Hopefully someone with more experience in akka internals will translate it properly.

Too bad, it would have been great to collaborate with the akka team :disappointed: , but I guess I'll be in another occasion.

**Comment by sirthias** [comment]
No problem. We will probably come back to your solution here when we tackle https://github.com/akka/akka/issues/16827.
Thanks again!

**Pull request closed without merging**
