### PR TITLE
Fix for issue #993

### PR DESCRIPTION
**Pull request by briandignan**
Gets the IP address string instead of the hostname string

### CODE REVIEW

**Comment by sirthias** [comment]
Thanks, Brian, for this PR!
(And sorry for taking so long to look at it.)
Unfortunately, as the discussion in https://github.com/spray/spray/issues/993 revealed, this fix is not yet good enough.

We just discussed the solution that we'd like to apply to this problem:
1. Try to call `InetSocketAddress::getHostString` per reflection. If this succeeds all is well.
2. If the reflection call fails (probably because the user is still on JDK 6) we fall back to the current behavior.

This should allow us to make use of the better API in JDK7+ while not giving up on JDK6 altogether.

Would you like to take a stab at this solution?

**Comment by briandignan** [comment]
I'll definitely take a stab at it. You know it's funny though.. Last night I had a dream about using reflection to solve this. Weird huh?

What's the proper way to submit an updated commit? Should I just submit a new commit to the existing PR? Thanks!

**Comment by sirthias** [comment]
Just `git push -f` into your branch to update this PR.
That'll be fine.
Thanks!

**Comment by briandignan** [comment]
Hey @sirthias, @jrudolph . Let me know what you think of the update. Since the Scala reflection API is still marked as experimental, I used the Java reflection API instead. If you prefer Scala reflection though, I can change it.  

If there's anything at all that you would do differently, definitely let me know! Digging into Spray has been a great learning experience, and I'm open to any feedback that you guys have. 

I did some manual testing before and after implementing the changes. The factors for the tests were:

- Java 1.7.0_67 / Java 1.6.0_65
- Fix to #993 / No fix 
- Request by IP / Request by Name

I manually tested all 8 combinations. In every test, I was requesting the root URL from www.google.com with SSL. Between each test, I flushed DNS on my Mac with " sudo killall -HUP mDNSResponder". 

What I saw in packet captures mostly matched what I was expecting. The behavior for Java 6 was the same with or without the fix, which was expected. In the Java 7 test where the fix was implemented and the request was sent to an IP, reverse DNS queries were no longer being sent (good). I did notice something strange about the other three Java 7 tests though.  DNS queries for "SOA local" were being sent after the 3-way TCP handshake but before the TLS Hello. This wasn't happening with Java 6. It could be something unique about my machine. Either way though, I wanted to make sure you guys were aware of the behavior.

**Comment by briandignan** [comment]
In case you're interested, here are the screenshots from the testing:

Java 6, Without fix, Request IP
java-6-without-fix-by-ip

Java 6, With fix, Request IP
java-6-with-fix-by-ip

Java 6, Without fix, Request Name
java-6-without-fix-by-name

Java 6, With fix, Request Name
java-6-with-fix-by-name

Java 7, Without fix, Request IP
java-7-without-fix-by-ip

Java 7, With fix, Request IP
java-7-with-fix-by-ip

Java 7, Without fix, Request Name
java-7-without-fix-by-name

Java 7, With fix, Request Name
java-7-with-fix-by-name

**Comment by sirthias** [comment]
Thanks for this work, Brian! Great analysis to demonstrate the effectiveness of the fix!

**Comment by briandignan** [comment]
Hey @sirthias. I amended the commit based on your comments so that additional reflection isn't required for subsequent creations of an SSLEngine object. Let me know what you think.

**Comment by briandignan** [comment]
Sounds good @sirthias . Is there a way for me to amend the commit without erasing all of your notes? I could do another commit, but I figured that you wouldn't want multiple commit related to the same issue in the git history.

**Comment by sirthias** [comment]
If you push -f into your branch and replace the existing commit the notes will still be available.
They will just be folded. So, no worries.

**Comment by sirthias** [comment]
Thanks, Brian, this looks good!
I'll wait until @jrudolph has seen this as well and then push the `merge` button.

**Comment by briandignan** [comment]
Open Source FTW!!

**Comment by jrudolph** [comment]
LGTM

**Comment by sirthias** [comment]
Ok, Brian, I am ready to merge now but realized that you still need to accept the [Typesage CLA](http://www.typesafe.com/contribute/cla/). It's a purely online process that should only take about 30 secs or so.
Would you be able to do this?
Ideally we'd like to publish a new release today and it'd be great, if we can get this fix in.
Thanks again!

**Comment by briandignan** [comment]
Done!

I attended Roland's presentation on Akka HTTP last week at Scala Days. It was really impressive. I can't wait to start using it!

**Comment by sirthias** [comment]
Excellent.
Thanks, Brian!

**Pull request merged**
