### PR TITLE
Updating the readme to have an EOL statement

### PR DESCRIPTION
**Pull request by adamdecaf**
Issue: https://github.com/spray/spray/issues/1116

Feel free to change around the wording. I've been trying to find an official EOL statement and ran into something from an akka release.

http://akka.io/news/2016/08/02/akka-2.4.9-RC1-released.html

### CODE REVIEW

**Comment by ktoso** [comment]
Thanks, it's true that now is the time to announce this more strongly than before.
We'll want to be a bit more specific than that, as well as link to 10.+ etc.

I'll build upon your PR tomorrow to get the message right - we also want the same on the website.

**Comment by adamdecaf** [comment]
Awesome, thanks!

**Comment by sirthias** [comment]
@ktoso I'll happily push an update to the website once we have an official wording for the deprecation notice.

**Comment by ktoso** [comment]
Note was added by @sirthias to the site: https://github.com/spray/spray/commit/67e1fe800956cef1d410b49ca6f88270a4b9be0d
And I'll update the README.

Thanks for the reminder @adamdecaf !

**Comment by ktoso** [comment]
Readme update: https://github.com/spray/spray/pull/1134

**Pull request closed without merging**
