### PR TITLE
= http: make `spray.http.RangeUnit.Bytes` a `case object`, closes #954

### LINKED ISSUE #954: Range.ByteUnit.Bytes isn't Serializable

### PR DESCRIPTION
**Pull request by sirthias**

### CODE REVIEW

**Comment by jrudolph** [comment]
There are also

 - `ContentRange.Unsatisfiable`
 - `LanguageRanges.*`
 - `HttpEncodingRange.*`
 - `Uri.Empty`

which would maybe also qualify as `case object`s.

**Comment by sirthias** [comment]
Yes, indeed. Thanks for digging these up!

**Comment by sirthias** [comment]
Fixed.

**Comment by jrudolph** [comment]
Cool, LGTM.

**Pull request merged**
