### PR TITLE
= http: Fixes mandatory quotation of realm, refs #1041

### PR DESCRIPTION
**Pull request by csomogyi**
Fixes mandatory quotation of realm in HTTP auth challenge.
According to
http://greenbytes.de/tech/webdav/draft-ietf-httpbis-p7-auth-25.html#rfc.section.2.2.p.4

### CODE REVIEW

**Comment by csomogyi** [comment]
`SslTlsSupportSpec` in the OpenJDK build has failed. Nothing to do with the `http` module.

Is it possible to rerun the test (could be a timing issue as the timeout was set to 1s, which can be short if the env was very busy during the build)? Or can the PR go further despite the failed build?

**Comment by csomogyi** [comment]
Mathias, I have another issue. I'd like to sign the CLA but on the project page I can find only Individual CLA and not Corporate. I'd need the latter. Could you pls send me such one for me?

**Comment by sirthias** [comment]
Thanks for the PR. Looks good!
Regarding the CLA, it looks like you already accepted it online with your GH user account, which is all we need. Do you need the corporate CLA nevertheless?

**Comment by csomogyi** [comment]
I discussed the CLA matter with my business partners and it's ok for now if I go with the individual CLA, which I sent in the meantime. Thanks!

**Comment by sirthias** [comment]
Excellent. Thanks, Csongor!
(Fixes #1041)

**Comment by jrudolph** [comment]
Nice, thanks. Port to akka-http in https://github.com/akka/akka/pull/17230

**Pull request merged**
